services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - ./node_modules/.prisma/:/app/node_modules/.prisma/
    env_file:
      - .env
    ports:
      - 3000:${APP_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - movies-api-postgres:/var/lib/postgresql/data

volumes:
  movies-api-postgres:
