services:
  api:
    container_name: movies-api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - ./node_modules/.prisma/:/app/node_modules/.prisma/
    env_file:
      - .env
    ports:
      - 3000:${APP_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: movies-db
